version: "2"

linters:
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - revive
    - bodyclose
    - sqlclosecheck
    - noctx
    - gosec

formatters:
  enable:
    - gofumpt
    - goimports
